version: 3
  
tasks:
  test:
    cmds:
      - go clean -testcache
      - go test -cover -race ./...
  cover:
    cmds:
      - go test -race -v -coverpkg=./... -coverprofile=c.out ./...
      - go tool cover -html="c.out"
      - rm c.out
  lint:
    cmds:
      - golangci-lint run
  lintfix:
    cmds:
      - golangci-lint run --fix
